// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `pcp.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __E__temp_testice1_testice1_pcp_h__
#define __E__temp_testice1_testice1_pcp_h__

#if !defined(ICE_STATIC_LIBS) && defined(_MSC_VER) && (!defined(_DLL) || !defined(_MT))
#	define ICE_STATIC_LIBS
#	ifdef _DEBUG
#		pragma comment(lib, "libbz2d.lib")
#	else
#		pragma comment(lib, "libbz2.lib")
#	endif
#	pragma comment(lib, "Rpcrt4.lib")
#	pragma comment(lib, "Iphlpapi.lib")
#	pragma comment(lib, "dbghelp.lib")
#endif

#ifdef _DEBUG
#pragma comment(lib, "iced.lib")
#pragma comment(lib, "iceutild.lib")
#else
#pragma comment(lib, "ice.lib")
#pragma comment(lib, "iceutil.lib")
#endif

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace MPcp
{

class IPcp;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::MPcp::IPcp>&);
::IceProxy::Ice::Object* upCast(::IceProxy::MPcp::IPcp*);

}

}

namespace MPcp
{

class IPcp;
bool operator==(const IPcp&, const IPcp&);
bool operator<(const IPcp&, const IPcp&);
::Ice::Object* upCast(::MPcp::IPcp*);
typedef ::IceInternal::Handle< ::MPcp::IPcp> IPcpPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::MPcp::IPcp> IPcpPrx;
void __patch(IPcpPtr&, const ::Ice::ObjectPtr&);

}

namespace MPcp
{

typedef ::std::vector< ::std::string> VectorString;

}

namespace MPcp
{

class Callback_IPcp_InvokeMethod_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_IPcp_InvokeMethod_Base> Callback_IPcp_InvokeMethodPtr;

}

namespace IceProxy
{

namespace MPcp
{

class IPcp : virtual public ::IceProxy::Ice::Object
{
public:

    ::MPcp::VectorString InvokeMethod(const ::std::string& strMethodName, const ::MPcp::VectorString& vecParams)
    {
        return InvokeMethod(strMethodName, vecParams, 0);
    }
    ::MPcp::VectorString InvokeMethod(const ::std::string& strMethodName, const ::MPcp::VectorString& vecParams, const ::Ice::Context& __ctx)
    {
        return InvokeMethod(strMethodName, vecParams, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_InvokeMethod(const ::std::string& strMethodName, const ::MPcp::VectorString& vecParams, const ::IceInternal::Function<void (const ::MPcp::VectorString&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_InvokeMethod(strMethodName, vecParams, 0, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_InvokeMethod(const ::std::string& strMethodName, const ::MPcp::VectorString& vecParams, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_InvokeMethod(strMethodName, vecParams, 0, ::Ice::newCallback(completed, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_InvokeMethod(const ::std::string& strMethodName, const ::MPcp::VectorString& vecParams, const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::MPcp::VectorString&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_InvokeMethod(strMethodName, vecParams, &ctx, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_InvokeMethod(const ::std::string& strMethodName, const ::MPcp::VectorString& vecParams, const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_InvokeMethod(strMethodName, vecParams, &ctx, ::Ice::newCallback(completed, sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_InvokeMethod(const ::std::string& strMethodName, const ::MPcp::VectorString& vecParams, const ::Ice::Context* ctx, const ::IceInternal::Function<void (const ::MPcp::VectorString&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception, const ::IceInternal::Function<void (bool)>& sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::MPcp::VectorString&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::MPcp::IPcpPrx __proxy = ::MPcp::IPcpPrx::uncheckedCast(__result->getProxy());
                ::MPcp::VectorString __ret;
                try
                {
                    __ret = __proxy->end_InvokeMethod(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::MPcp::VectorString&)> _response;
        };
        return begin_InvokeMethod(strMethodName, vecParams, ctx, new Cpp11CB(response, exception, sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_InvokeMethod(const ::std::string& strMethodName, const ::MPcp::VectorString& vecParams)
    {
        return begin_InvokeMethod(strMethodName, vecParams, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_InvokeMethod(const ::std::string& strMethodName, const ::MPcp::VectorString& vecParams, const ::Ice::Context& __ctx)
    {
        return begin_InvokeMethod(strMethodName, vecParams, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_InvokeMethod(const ::std::string& strMethodName, const ::MPcp::VectorString& vecParams, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_InvokeMethod(strMethodName, vecParams, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_InvokeMethod(const ::std::string& strMethodName, const ::MPcp::VectorString& vecParams, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_InvokeMethod(strMethodName, vecParams, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_InvokeMethod(const ::std::string& strMethodName, const ::MPcp::VectorString& vecParams, const ::MPcp::Callback_IPcp_InvokeMethodPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_InvokeMethod(strMethodName, vecParams, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_InvokeMethod(const ::std::string& strMethodName, const ::MPcp::VectorString& vecParams, const ::Ice::Context& __ctx, const ::MPcp::Callback_IPcp_InvokeMethodPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_InvokeMethod(strMethodName, vecParams, &__ctx, __del, __cookie);
    }

    ::MPcp::VectorString end_InvokeMethod(const ::Ice::AsyncResultPtr&);
    
private:

    ::MPcp::VectorString InvokeMethod(const ::std::string&, const ::MPcp::VectorString&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_InvokeMethod(const ::std::string&, const ::MPcp::VectorString&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<IPcp> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<IPcp*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<IPcp> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<IPcp*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<IPcp> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<IPcp*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<IPcp> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<IPcp*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<IPcp> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<IPcp*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<IPcp> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<IPcp*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<IPcp> ice_secure(bool __secure) const
    {
        return dynamic_cast<IPcp*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<IPcp> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<IPcp*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<IPcp> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<IPcp*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<IPcp> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<IPcp*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<IPcp> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<IPcp*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<IPcp> ice_twoway() const
    {
        return dynamic_cast<IPcp*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<IPcp> ice_oneway() const
    {
        return dynamic_cast<IPcp*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<IPcp> ice_batchOneway() const
    {
        return dynamic_cast<IPcp*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<IPcp> ice_datagram() const
    {
        return dynamic_cast<IPcp*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<IPcp> ice_batchDatagram() const
    {
        return dynamic_cast<IPcp*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<IPcp> ice_compress(bool __compress) const
    {
        return dynamic_cast<IPcp*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<IPcp> ice_timeout(int __timeout) const
    {
        return dynamic_cast<IPcp*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<IPcp> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<IPcp*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<IPcp> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<IPcp*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace MPcp
{

class IPcp : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual ::MPcp::VectorString InvokeMethod(const ::std::string&, const ::MPcp::VectorString&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace MPcp
{

class IPcp : virtual public ::IceDelegate::MPcp::IPcp,
             virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual ::MPcp::VectorString InvokeMethod(const ::std::string&, const ::MPcp::VectorString&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace MPcp
{

class IPcp : virtual public ::IceDelegate::MPcp::IPcp,
             virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual ::MPcp::VectorString InvokeMethod(const ::std::string&, const ::MPcp::VectorString&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace MPcp
{

class IPcp : virtual public ::Ice::Object
{
public:

    typedef IPcpPrx ProxyType;
    typedef IPcpPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual ::MPcp::VectorString InvokeMethod(const ::std::string&, const ::MPcp::VectorString&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___InvokeMethod(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const IPcp& l, const IPcp& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const IPcp& l, const IPcp& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace MPcp
{

template<class T>
class CallbackNC_IPcp_InvokeMethod : public Callback_IPcp_InvokeMethod_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::MPcp::VectorString&);

    CallbackNC_IPcp_InvokeMethod(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::MPcp::IPcpPrx __proxy = ::MPcp::IPcpPrx::uncheckedCast(__result->getProxy());
        ::MPcp::VectorString __ret;
        try
        {
            __ret = __proxy->end_InvokeMethod(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_IPcp_InvokeMethodPtr
newCallback_IPcp_InvokeMethod(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::MPcp::VectorString&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_IPcp_InvokeMethod<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_IPcp_InvokeMethodPtr
newCallback_IPcp_InvokeMethod(T* instance, void (T::*cb)(const ::MPcp::VectorString&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_IPcp_InvokeMethod<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_IPcp_InvokeMethod : public Callback_IPcp_InvokeMethod_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::MPcp::VectorString&, const CT&);

    Callback_IPcp_InvokeMethod(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::MPcp::IPcpPrx __proxy = ::MPcp::IPcpPrx::uncheckedCast(__result->getProxy());
        ::MPcp::VectorString __ret;
        try
        {
            __ret = __proxy->end_InvokeMethod(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_IPcp_InvokeMethodPtr
newCallback_IPcp_InvokeMethod(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::MPcp::VectorString&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_IPcp_InvokeMethod<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_IPcp_InvokeMethodPtr
newCallback_IPcp_InvokeMethod(T* instance, void (T::*cb)(const ::MPcp::VectorString&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_IPcp_InvokeMethod<T, CT>(instance, cb, excb, sentcb);
}

}

#endif
